= JoinFaces Reference Guide
Marcelo Fernandes <persapiens@joinfaces.org>; Lars Grefer <larsgrefer@joinfaces.org>
:toc: left
:icons: font
:stylesheet: asciidoctor.css
:source-highlighter: prettify
:sectnums:
:sectanchors:
:hide-uri-scheme:

== About the Documentation

The documentation of JoinFaces {revnumber} consists of two parts:

- This Reference Guide
- The Javadoc API

The latest copy of the user guide is available at https://docs.joinfaces.org/current/reference +
and the corresponding javadocs can be found at https://docs.joinfaces.org/current/api.

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.

== Getting Started

NOTE: If you're not familiar with _Spring Boot_, you should read its
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#getting-started[Getting Started guide] first.

.Official example projects
|===
|Build tool \ packaging |`jar` |`war`

|https://maven.apache.org/[Maven]
|https://github.com/joinfaces/joinfaces-maven-jar-example[maven-jar-example]
|https://github.com/joinfaces/joinfaces-maven-war-example[maven-war-example]

|https://gradle.org/[Gradle]
|https://github.com/joinfaces/joinfaces-gradle-jar-example[gradle-jar-example]
|https://github.com/joinfaces/joinfaces-gradle-war-example[gradle-war-example]

|===

=== System Requirements

Unless otherwise noted, JoinFaces has the same system requirements as
https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#getting-started-system-requirements[_Spring Boot {spring-boot-version}_].

When using Java 9 or higher, make sure to use JoinFaces only on the classpath and not on the modulepath.

[#bom]
=== Dependency Management

Each release of JoinFaces provides a curated list of dependencies that it supports.
This list is an extension of
https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#using-boot-dependency-management[Spring Boot's dependency management] and therefore works exactly the same way.

The `joinfaces-dependencies` BOM also imports the `spring-boot-dependencies` BOM.
If you want to override the imported Spring Boot version, make sure to specify the
Spring Boot BOM after the JoinFaces one.

=== Maven

NOTE: Please also consult the official Spring Boot documentation: https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#using-boot-maven[Link]

[source,xml,subs=attributes+]
----
<project>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>{spring-boot-version}</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <joinfaces.version>{revnumber}</joinfaces.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.joinfaces</groupId>
                <artifactId>joinfaces-dependencies</artifactId>
                <version>${joinfaces.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.joinfaces</groupId>
            <artifactId>jsf-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.joinfaces</groupId>
                    <artifactId>joinfaces-maven-plugin</artifactId>
                    <version>${joinfaces.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>classpath-scan</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.joinfaces</groupId>
                <artifactId>joinfaces-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
----

=== Gradle

NOTE: Please also consult the official Spring Boot documentation: https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#using-boot-gradle[Link]

[source,groovy,subs=attributes+]
----
plugins {
    id 'org.joinfaces' version '{revnumber}'
}
apply plugin: 'java' //or 'war'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

dependencies {
    compile 'org.joinfaces:jsf-spring-boot-starter'

    testCompile 'org.springframework.boot:spring-boot-starter-test'
}
----

==== Not using the JoinFaces gradle plugin

[source,groovy,subs=attributes+]
----
plugins {
    id 'org.springframework.boot' version '{spring-boot-version}'
}
apply plugin: 'java' //or 'war'
apply plugin: 'io.spring.dependency-management'

dependencyManagement {
    imports {
        mavenBom 'org.joinfaces:joinfaces-dependencies:{revnumber}'
    }
}

dependencies {
    compile 'org.joinfaces:jsf-spring-boot-starter'

    testCompile 'org.springframework.boot:spring-boot-starter-test'
}
----

== Build Tools integration

=== Maven Plugin

JoinFaces provides `org.joinfaces:joinfaces-maven-plugin` https://maven.apache.org[Maven] plugin to configure a classpath scan at build-time in order to reduce the startup time of applications which use an embedded servlet container.

If you have any problems with the classpath scan, you can remove it from plugin section in your `pom.xml` or disable it:
[source,sh]
----
-Djoinfaces.skip=true
----


=== Gradle Plugin

JoinFaces provides some https://gradle.org/[Gradle] plugins to simplify the development.

NOTE: When using the JoinFaces Gradle plugins, you might want to use the https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#using-boot-gradle[Spring Boot gradle plugin], too.

==== `org.joinfaces`

The `org.joinfaces` plugin is the main plugin. It does nothing on it's own, but conditionally applies
the other plugin in reaction to the plugins present in the project.

TIP: If defaults in the `org.joinfaces` plugin don't work for you, you can just include the sub-plugins you need instead.

==== `org.joinfaces.dependency-management`

This plugin is applied by the main plugin if the https://github.com/spring-gradle-plugins/dependency-management-plugin[`io.spring.dependency-management` plugin] is applied to the current project.
If this plugin is applied directly it will apply the `io.spring.dependency-management` itself.

In both cases it configures the dependency management plugin to use the JoinFaces <<bom>>.

This is similar to what the https://docs.spring.io/spring-boot/docs/{spring-boot-version}/gradle-plugin/reference/html/#managing-dependencies[Spring Boot Gradle plugin does].

==== `org.joinfaces.classpath-scan`

This plugin configures a classpath scan at build-time in order to reduce the startup time of applications which use an
embedded servlet container.

For each source-set the `runtimeClasspath` configuration and the output of the compile tasks for `java`, `groovy`,
`scala` and `kotlin` will be scanned.

If you have any problems with the classpath scan, you can disable it:
[source,groovy]
----
scanClasspath.enabled = false
----

== JoinFaces Features

=== Starters

There are seventeen JoinFaces Starters available: six basic starters, two utility starters, one meta starter, six component starters, one theme starter and one extra starter.

While most of the starters can be combined, some starters are mutually exclusive:

- `tomcat-spring-boot-starter`, `jetty-spring-boot-starter` and `undertow-spring-boot-starter`
- `mojarra-spring-boot-starter` and `myfaces-spring-boot-starter`
- `omnifaces1-spring-boot-starter` and `omnifaces3-spring-boot-starter`

You can use the table below to discover the starters that fit your needs.

.JoinFaces starters
[%autowidth]
|===========
|Starter |Description

|tomcat-spring-boot-starter
|Basic starter for https://tomcat.apache.org/[Tomcat] servlet container.

|jetty-spring-boot-starter
|Basic starter for https://www.eclipse.org/jetty[Jetty] servlet container.

|undertow-spring-boot-starter
|Basic starter for http://undertow.io[Undertow] servlet container.

|mojarra-spring-boot-starter
|Basic starter for https://javaee.github.io/javaserverfaces-spec/[Mojarra] JSF implementation.

|myfaces-spring-boot-starter
|Basic starter for https://myfaces.apache.org/[MyFaces] JSF implementation.

|weld-spring-boot-starter
|Basic starter for https://weld.cdi-spec.org/[Weld] CDI Reference Implementation.

|omnifaces1-spring-boot-starter
|Utility starter for https://omnifaces.org/[OmniFaces] JSF utility library.

|omnifaces3-spring-boot-starter
|Utility starter for https://omnifaces.org/[OmniFaces] JSF utility library. Pulls `weld-spring-boot-starter`.

|jsf-spring-boot-starter
|Meta starter that pulls `tomcat-spring-boot-starter`, `mojarra-spring-boot-starter` and `omnifaces1-spring-boot-starter`.

|primefaces-spring-boot-starter
|Component starter for https://primefaces.org[PrimeFaces], and https://primefaces-extensions.github.io/[PrimeFaces Extensions] JSF Component libraries. Pulls `jsf-spring-boot-starter`.

|bootsfaces-spring-boot-starter
|Component starter for https://bootsfaces.net[BootsFaces] JSF Component library. Pulls `jsf-spring-boot-starter`.

|butterfaces-spring-boot-starter
|Component starter for http://butterfaces.org[ButterFaces] JSF Component library. Pulls `jsf-spring-boot-starter`.

|icefaces-spring-boot-starter
|Component starter for https://www.icesoft.org/java/projects/ICEfaces/overview.jsf[IceFaces] JSF Component library. Pulls `jsf-spring-boot-starter`.

|richfaces-spring-boot-starter
|Component starter for https://github.com/richfaces/richfaces[RichFaces] JSF Component library. Pulls `jsf-spring-boot-starter`.

|angularfaces-spring-boot-starter
|Component starter for https://angularfaces.net[AngularFaces] JSF Component library. Pulls `jsf-spring-boot-starter`.

|adminfaces-spring-boot-starter
|Template and Theme starter for https://adminfaces.github.io/site/[AdminFaces]. Pulls `primefaces-spring-boot-starter`.

|rewrite-spring-boot-starter
|Extra starter for https://github.com/ocpsoft/rewrite[Ocpsoft Rewrite] URL Rewriting Tool.
|===========

==== Not using Tomcat or Mojarra
The `jsf-spring-boot-starter` pulls tomcat and mojarra as defaults. If you want to change this, you have to exclude one starter and pull another one instead.

The principle behind this is the same as described here:

- https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#howto-use-another-web-server[Use Another Web Server]
- https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#howto-configure-log4j-for-logging[Configure Log4j for Logging]

===== Example: Using MyFaces instead of Mojarra
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>org.joinfaces</groupId>
        <artifactId>jsf-spring-boot-starter</artifactId>
        <exclusions>
            <exclusion>
                <groupId>org.joinfaces</groupId>
                <artifactId>mojarra-spring-boot-starter</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>org.joinfaces</groupId>
        <artifactId>myfaces-spring-boot-starter</artifactId>
    </dependency>
</dependencies>
----

[source,groovy]
----
dependencies {
    compile ("org.joinfaces:jsf-spring-boot-starter") {
        exclude module: "mojarra-spring-boot-starter"
    }
    compile "org.joinfaces:myfaces-spring-boot-starter"
    // ...
}
----

=== Servlet-Context Init-Parameters

JSF implementations and JSF component libraries are usually configured using servlet context init parameters in `web.xml`:

[source,xml]
----
<context-param>
    <param-name>javax.faces.PROJECT_STAGE</param-name>
    <param-value>Development</param-value>
</context-param>
<context-param>
    <param-name>primefaces.THEME</param-name>
    <param-value>omega</param-value>
</context-param>
----

_Spring Boot_ based applications -- especially when using `jar`-packaging -- usually don't have a `web.xml` file.
Therefore JoinFaces maps these options to
https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#boot-features-external-config[_Spring Boot_ properties]:

[source,properties]
----
jsf.project-stage=development
jsf.primefaces.theme=omega
----

The full list of all properties can be found in the chapter <<properties>>.

NOTE: Most of these properties default to `null`, so the corresponding parameter isn't set to the servlet-context.
This allows the underlying library to use their own default behaviour.

[TIP]
====
If you need a to set a parameter which isn't specially handled by JoinFaces, you can still set it using this generic way:

[source,properties,subs="+quotes"]
----
server.servlet.context-parameters._javax.faces.PROJECT_STAGE_=Development
server.servlet.context-parameters._primefaces.THEME_=omega
----
====

=== JSF and CDI scope-annotations support

JSF and CDI scope-annotations are automatically supported.

The following annotations can be used to define the scope of Spring beans:

==== Spring's default annotations

- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/context/annotation/ApplicationScope.html[`@org.springframework.web.context.annotation.ApplicationScope`] or https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Scope.html[`@org.springframework.context.annotation.Scope("application")`]
- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/context/annotation/RequestScope.html[`@org.springframework.web.context.annotation.RequestScope`] or https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Scope.html[`@org.springframework.context.annotation.Scope("request")`]
- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/context/annotation/SessionScope.html[`@org.springframework.web.context.annotation.SessionScope`] or https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Scope.html[`@org.springframework.context.annotation.Scope("session")`]
- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Scope.html[`@org.springframework.context.annotation.Scope("view")`]

==== New JSF Scope annotation (JSF >= 2.2)

- https://docs.oracle.com/javaee/7/api/javax/faces/view/ViewScoped.html[`@javax.faces.view.ViewScoped`] (mapped to Joinfaces' `view` scope)

==== Old JSF Scope annotations (JSF <= 2.1)

CAUTION: The following annotations are only supported for backwards compatibility.
New applications should only use the annotations above.

- https://docs.oracle.com/javaee/7/api/javax/faces/bean/ApplicationScoped.html[`@javax.faces.bean.ApplicationScoped`] (mapped to Spring's `application` scope)
- https://docs.oracle.com/javaee/7/api/javax/faces/bean/NoneScoped.html[`@javax.faces.bean.NoneScoped`] (mapped to Spring's `prototype` scope)
- https://docs.oracle.com/javaee/7/api/javax/faces/bean/RequestScoped.html[`@javax.faces.bean.RequestScoped`] (mapped to Spring's `request` scope)
- https://docs.oracle.com/javaee/7/api/javax/faces/bean/SessionScoped.html[`@javax.faces.bean.SessionScoped`] (mapped to Spring's `session` scope)
- https://docs.oracle.com/javaee/7/api/javax/faces/bean/ViewScoped.html[`@javax.faces.bean.ViewScoped`] (mapped to Joinfaces' `view` scope)

==== CDI Annotations

- https://docs.oracle.com/javaee/7/api/javax/enterprise/context/ApplicationScoped.html[`@javax.enterprise.context.ApplicationScoped`] (mapped to Spring's `application` scope)
- https://docs.oracle.com/javaee/7/api/javax/enterprise/context/ConversationScoped.html[`@javax.enterprise.context.ConversationScoped`] (mapped to Spring's `session` scope)
- https://docs.oracle.com/javaee/7/api/javax/enterprise/context/RequestScoped.html[`@javax.enterprise.context.RequestScoped`] (mapped to Spring's `request` scope)
- https://docs.oracle.com/javaee/7/api/javax/enterprise/context/SessionScoped.html[`@javax.enterprise.context.SessionScoped`] (mapped to Spring's `session` scope)

=== Spring Security JSF Facelet Tag support

JoinFaces enables Spring Security JSF Facelet Tag support in order to secure JSF pages.

Namespace: **http://www.springframework.org/security/tags**

.Spring Security JSF Facelet Tags
[options="header"]
|===========
| Tag | Description
| authorize | perform Spring Security authorization decisions, using attributes: ifAnyGranted, ifAllGranted, ifNotGranted, access, url, method, var.
| anonymous | verify if the user is anonymous.
|authenticated | verify if the user is not anonymous.
| fullyAuthenticated | verify if the is not an anonymous or a remember-me user.
|===========

.Spring Security JSF Facelet Functions
[options="header"]
|===========
| Function | Description
| areAllGranted | returns true if the user has all of of the given authorities.
| areAnyGranted | returns true if the user has any of the given authorities.
| areNotGranted | returns true if the user does not have any of the given authorities.
| isAllowed | returns true if the user is allowed to access the given URL and HTTP method combination.
| isAnonymous | returns true if user is anonymous.
| isAuthenticated | returns true if the user is not anonymous.
| isFullyAuthenticated | returns true if the is not an anonymous or a remember-me user.
|===========


[[properties]]
[appendix]
== Configuration Properties

This appendix contains a alphabetical list of all properties handled by JoinFaces.

NOTE: The properties already supported by _Spring Boot_ itself aren't listed here again.
They can be found https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#common-application-properties[in
the corresponding chapter of the _Spring Boot Reference Guide_].

include::generated/_properties.adoc[]

[appendix]
== Dependency versions

NOTE: The versions already handled by the dependency management of _Spring Boot_ aren't listed here again.
The can be found in
https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#appendix-dependency-versions[the
corresponding chapter of the _Spring Boot Reference Guide_].

include::generated/_versions.adoc[]
