= JoinFaces Documentation
Marcelo Fernandes <persapiens@joinfaces.org>; Lars Grefer <larsgrefer@joinfaces.org>
:toc: left
:stylesheet: asciidoctor.css
:source-highlighter: prettify
:sectnums:
:sectanchors:

IMPORTANT: This documentation is still under construction.

== Using JoinFaces

.Official example projects
|===
|Build tool \ packaging |`jar` |`war`

|https://maven.apache.org/[Maven]
|https://github.com/joinfaces/joinfaces-maven-jar-example[maven-jar-example]
|https://github.com/joinfaces/joinfaces-maven-war-example[maven-war-example]

|https://gradle.org/[Gradle]
|https://github.com/joinfaces/joinfaces-gradle-jar-example[gradle-jar-example]
|https://github.com/joinfaces/joinfaces-gradle-war-example[gradle-war-example]

|===

=== System Requirements

.System Requirements
|===
|Joinfaces |Java |Spring Boot |JSF

|3.3        |1.8 to 11  |2.1    |2.0 to 2.3
|3.0 to 3.2 |1.8        |2.0    |2.0 to 2.3
|2.x        |1.6 to 1.8 |1.x    |2.0 to 2.2

|===

This are the combinations we have tested and expect to work, but depending on the features you are using, other combinations might work, too.

[#bom]
=== Dependency Management

Each release of JoinFaces provides a curated list of dependencies that it supports.
This list is an extension of
https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#using-boot-dependency-management[Spring Boot's dependency management] and therefore works exactly the same way.

The `joinfaces-dependencies` BOM also imports the `spring-boot-dependencies` BOM.
If you want to override the imported Spring Boot version, make sure to specify the
Spring Boot BOM after the JoinFaces one.

=== Maven

NOTE: Please also consult the official Spring Boot documentation: https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#using-boot-maven[Link]

[source,xml,subs=attributes+]
----
<project>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>{spring-boot-version}</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <joinfaces.version>{revnumber}</joinfaces.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.joinfaces</groupId>
                <artifactId>joinfaces-dependencies</artifactId>
                <version>${joinfaces.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.joinfaces</groupId>
            <artifactId>jsf-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.joinfaces</groupId>
                    <artifactId>joinfaces-maven-plugin</artifactId>
                    <version>${joinfaces.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>classpath-scan</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.joinfaces</groupId>
                <artifactId>joinfaces-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
----

=== Gradle

NOTE: Please also consult the official Spring Boot documentation: https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#using-boot-gradle[Link]

[source,groovy,subs=attributes+]
----
plugins {
    id 'org.joinfaces' version '{revnumber}'
}
apply plugin: 'java' //or 'war'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

dependencies {
    compile 'org.joinfaces:jsf-spring-boot-starter'

    testCompile 'org.springframework.boot:spring-boot-starter-test'
}
----

==== Not using the JoinFaces gradle plugin

[source,groovy,subs=attributes+]
----
plugins {
    id 'org.springframework.boot' version '{spring-boot-version}'
}
apply plugin: 'java' //or 'war'
apply plugin: 'io.spring.dependency-management'

dependencyManagement {
    imports {
        mavenBom 'org.joinfaces:joinfaces-dependencies:{revnumber}'
    }
}

dependencies {
    compile 'org.joinfaces:jsf-spring-boot-starter'

    testCompile 'org.springframework.boot:spring-boot-starter-test'
}
----

== Maven Plugin

JoinFaces provides `org.joinfaces:joinfaces-maven-plugin` https://maven.apache.org[Maven] plugin to configure a classpath scan at build-time in order to reduce the startup time of applications which use an embedded servlet container.

If you have any problems with the classpath scan, you can remove it from plugin section in your `pom.xml` or disable it:
[source,groovy,subs=attributes+]
----
-Djoinfaces.skip = true
----


== Gradle Plugin

JoinFaces provides some https://gradle.org/[Gradle] plugins to simplify the development.

NOTE: When using the JoinFaces Gradle plugins, you might want to use the https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#using-boot-gradle[Spring Boot gradle plugin], too.

=== `org.joinfaces`

The `org.joinfaces` plugin is the main plugin. It does nothing on it's own, but conditionally applies
the other plugin in reaction to the plugins present in the project.

TIP: If defaults in the `org.joinfaces` plugin don't work for you, you can just include the sub-plugins you need instead.

=== `org.joinfaces.dependency-management`

This plugin is applied by the main plugin if the https://github.com/spring-gradle-plugins/dependency-management-plugin[`io.spring.dependency-management` plugin] is applied to the current project.
If this plugin is applied directly it will apply the `io.spring.dependency-management` itself.

In both cases it configures the dependency management plugin to use the JoinFaces <<bom>>.

This is similar to what the https://docs.spring.io/spring-boot/docs/{spring-boot-version}/gradle-plugin/reference/html/#managing-dependencies[Spring Boot Gradle plugin does].

=== `org.joinfaces.classpath-scan`

This plugin configures a classpath scan at build-time in order to reduce the startup time of applications which use an
embedded servlet container.

For each source-set the `runtimeClasspath` configuration and the output of the compile tasks for `java`, `groovy`,
`scala` and `kotlin` will be scanned.

If you have any problems with the classpath scan, you can disable it:
[source,groovy,subs=attributes+]
----
scanClasspath.enabled = false
----

== Features

=== Servlet-Context Init-Parameters

JSF implementations and JSF component libraries are usually configured using servlet context init parameters in `web.xml`:

[source,xml]
----
<context-param>
    <param-name>javax.faces.PROJECT_STAGE</param-name>
    <param-value>Development</param-value>
</context-param>
<context-param>
    <param-name>primefaces.THEME</param-name>
    <param-value>omega</param-value>
</context-param>
----

_Spring Boot_ based applications -- especially when using `jar`-packaging -- usually don't have a `web.xml` file.
Therefore JoinFaces maps these options to
https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#boot-features-external-config[_Spring Boot_ properties]:

[source,properties]
----
jsf.project-stage=development
jsf.primefaces.theme=omega
----

The full list of all properties can be found in the chapter <<properties>>.

[TIP]
====
If you need a to set a parameter which isn't specially handled by JoinFaces, you can still set it using this generic way:

[source,properties,subs="+quotes"]
----
server.servlet.context-parameters._javax.faces.PROJECT_STAGE_=Development
server.servlet.context-parameters._primefaces.THEME_=omega
----
====

[[properties]]
[appendix]
== Properties

This appendix contains a alphabetical list of all properties handled by JoinFaces.

NOTE: The properties already supported by _Spring Boot_ itself aren't listed here again.
They can be found https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#common-application-properties[in
the corresponding chapter of the _Spring Boot Reference Guide_]

include::generated/_properties.adoc[]
