description = 'PrimeFaces Spring Boot Starter'
tasks.named("jar", Jar) {
    manifest.attributes('Automatic-Module-Name': 'joinfaces.starter.primefaces')
}

dependencies {
    api project(':joinfaces-starters:faces-spring-boot-starter')
    api 'org.primefaces:primefaces'
    api 'org.primefaces:primefaces-themes'
    api 'org.primefaces.extensions:primefaces-extensions'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
